# Generated by Django 3.1.3 on 2020-11-28 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='start_date',
            new_name='date_joined',
        ),
    ]
