# Generated by Django 3.1.3 on 2020-11-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201129_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.URLField(default='https://res.cloudinary.com/victormainak/image/upload/v1606634881/icons8-male-user-100_zratap.png'),
        ),
    ]
