# Generated by Django 3.1.3 on 2020-11-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201129_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='project',
            name='site_url',
            field=models.URLField(default='https://res.cloudinary.com/victormainak/image/upload/v1606635375/default_image_01_x3tuoe.png'),
        ),
    ]
