# Generated by Django 3.1.3 on 2020-11-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201129_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_media',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
