# Generated by Django 3.1.3 on 2020-11-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201129_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='landing_page_image',
            field=models.URLField(default='https://res.cloudinary.com/victormainak/image/upload/v1606635375/default_image_01_x3tuoe.png'),
        ),
        migrations.AlterField(
            model_name='project',
            name='site_url',
            field=models.URLField(),
        ),
    ]
